### PR TITLE
Bug #12: added case insensitivity to the category search

### LINKED ISSUE #12: (My Resources) Searching by name in resources tables should be case-insensitivity
When you are trying to search a resource by name, it shouldn`t be case-sensitive

### PR DESCRIPTION
**Pull request by SeredenkoDS**
Pretty straightforward, only one line of code is changed.

To test the difference (on develop branch and/or after doing "git checkout bug/12/make-search-case-insensitive "):
1. Log in as tutor
2. Go to "My Resources" http://localhost:3000/my-resources => Categories => create some categories with upper- and lowercase
3. Use the search field. Notice that the search is case-sensitive on develop and case-insensitive (bugfix) on this new branch.

Also:
— apparently the search doesn't support spaces (not sure if intended or a separate bug)
— "Questions" also has a search field, but I was unable to test anything there ("Save" button stays inactive when I try to create a question), and from the description of the bug I'm not sure if only category search is affected, or is it category+question... if it's the latter, I guess I could hold the issue for longer until question saving is fixed, and then touch this bug again.

### CODE REVIEW

**Review by grbvtsk — APPROVED** [review]

**Review by SachkovaYuliia — APPROVED** [review]

**Review by HalynaProlubshchykova — APPROVED** [review]

File: src/controllers/resourcesCategory.js [hunk 1]
```diff
@@ -16,7 +16,7 @@ const getResourcesCategories = async (req, res) => {
   const { id: author } = req.user
   const { name, sort, skip, limit } = req.query
 
-  const match = getMatchOptions({ author, name: getRegex(name) })
+  const match = getMatchOptions({ author, name: { ...getRegex(name), $options: 'i' } }) //added case insensitivity
```
Comment (vlad-khrychov) [inline src/controllers/resourcesCategory.js]:
```suggestion
  const match = getMatchOptions({ author, name: { ...getRegex(name), $options: 'i' } })
```

**Review by vlad-khrychov — APPROVED** [review]
Do not forget to delete the comment before merge
